import { buildTokensJson } from '@/design/tokens';

/**
 * GET /design/tokens.json
 *
 * Design tokens as JSON. Generated by buildTokensJson(), the same module
 * that generates /design/tokens.css and the <head> variables, so the three
 * cannot disagree. scripts/verify-tokens.mjs asserts that byte-for-byte.
 */
export const dynamic = 'force-static';

export function GET() {
  return new Response(JSON.stringify(buildTokensJson(), null, 2), {
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'access-control-allow-origin': '*',
      'cache-control': 'public, max-age=0, s-maxage=3600, stale-while-revalidate=86400',
    },
  });
}
