backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Cover Image", name: "cover_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "drafts"
    label: "Drafts"
    folder: "_archive"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: false}
      - {label: "Cover Image", name: "cover_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}