name: Deploy Jekyll site to Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        
      - name: Debug - List posts before build
        run: |
          echo "=== Posts in _posts directory ==="
          ls -la _posts/
          echo "=== Content of first few posts ==="
          head -10 _posts/*.md
          
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}" --verbose
        env:
          JEKYLL_ENV: production
          
      - name: Debug - Check build output
        run: |
          echo "=== _site directory contents ==="
          ls -la _site/
          echo "=== Check if blog page was generated ==="
          ls -la _site/blog/ 2>/dev/null || echo "No blog directory"
          echo "=== Check individual post pages ==="
          ls -la _site/test/ 2>/dev/null || echo "No test post directory"
          ls -la _site/music/ 2>/dev/null || echo "No music post directory"
          echo "=== Blog page content ==="
          cat _site/blog/index.html 2>/dev/null || echo "No blog/index.html"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4